trigger:
- master

pr:
- master

jobs:
  - job: x64
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        set -ex
        docker run -v $PWD:/t debian:unstable-slim /bin/bash -c "set -ex; apt update; apt install -y libedit-dev nasm gcc make; cd /t; CC=gcc make"
    - bash: |
        set -ex
        docker run -v $PWD:/t debian:unstable-slim /bin/bash -c "set -ex; apt update; apt install -y libedit-dev nasm make clang; cd /t; CC=clang make"