trigger:
- master

pr:
- master

jobs:
  - job: x64
    pool:
      vmImage: 'ubuntu-latest'
    container: debian:unstable-slim
    steps:
    - script: sudo apt-get install -y libedit-dev nasm clang
    - script: CC=gcc make
    - script: CC=clang make